apiVersion: v1
kind: Pod
metadata:
  name: storagedemo
  labels:
    name: pvcdemo
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
      volumeMounts:
        - name: pvstor
          mountPath: /usr/share/nginx/html
  volumes:
    - name: pvstor
      persistentVolumeClaim:
        claimName: mypvc
