apiVersion: v1
kind: persistentvolume
metadata:
  name: pv01
spec:
  storageClassName: admstor
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/pv01
---
apiVersion: v1
kind: persistentvolumeclaim
metadata:
  name: mypvc
spec:
  storageCLassName: admstor
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
